# Generated by Django 5.2.9 on 2025-12-03 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="club",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="core.club",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="role",
            unique_together={("name", "club")},
        ),
    ]
