# Generated by Django 5.2.9 on 2025-12-03 23:47

import django.db.models.deletion
import k9club.utils.slugs
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_role_club_alter_role_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="members",
            field=models.ManyToManyField(
                related_name="clubs",
                through="core.ClubUser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="slug",
            field=models.SlugField(
                default=k9club.utils.slugs.generate_slug, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="clubuser",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="club_users",
                to="core.club",
            ),
        ),
        migrations.AlterField(
            model_name="clubuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="club_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
