# Generated by Django 6.0 on 2025-12-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_club_members_alter_club_slug_alter_clubuser_club_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
